clone_depth: 5
 
environment:
    access_token:
        secure: h3bGXp4ofXUHaQqTsHJKPEA5sbXPFipWi5gSPB/VSMcS+VGiWj69xLcnLVsrB/n/
install:
    - ps: Install-Product node 
    - node --version
    - npm --version
    - npm install
    - npm install hexo-cli -g
    #- npm install hexo-deployer-git --save
    #- npm install hexo-generator-archive --save
    #######其他插件#########
    - npm install hexo-theme-next   # 下载最新版本的next主题
    - npm install hexo-abbrlink --save # 编写永久链接
    - npm install hexo-generator-searchdb --save  #本地搜索
    - npm install hexo-neat --save  # 静态压缩
    - npm install hexo-filter-nofollow --save    # 防跟随
    - npm install hexo-image-link --save
    #- npm install hexo-renderer-marked    # 加载图片
    - npm uninstall hexo-generator-index --save
    - npm install hexo-generator-index-pin-top --save  #置顶

    - npm install hexo-helper-live2d --save     #宠物
    - npm install live2d-widget-model-tororo
    - npm install hexo-generator-sitemap --save #谷歌检索
    - npm install hexo-generator-baidu-sitemap --save #百度检索
    - npm install hexo-word-counter   #统计文章字数

    #######################
    - npm ls --depth 0  #检查安装的插件
    
build_script:
    - hexo generate
    
artifacts:
    - path: public
    
on_success:
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "%GIT_USER_EMAIL%"
    - git config --global user.name "%GIT_USER_NAME%"
    - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
    - cd %TEMP%\static-site
    - del * /f /q
    - for /d %%p IN (*) do rmdir "%%p" /s /q
    - SETLOCAL EnableDelayedExpansion & robocopy "%APPVEYOR_BUILD_FOLDER%\public" "%TEMP%\static-site" /e & IF !ERRORLEVEL! EQU 1 (exit 0) ELSE (IF !ERRORLEVEL! EQU 3 (exit 0) ELSE (exit 1))
    - git add -A
    - git commit -m "Update Static Site"
    - git push origin %TARGET_BRANCH%
    - appveyor AddMessage "Static Site Updated"